### ISSUE TITLE
@types Iterator not identical

### ISSUE THREAD

**Issue by spiritguide7** [KillerCodeMonkey/ngx-quill-example#1]
Results of npm run build
> exmplate-ngx-quill@0.0.0 build C:\Users\Jack\Documents\ang2\ngx-quill-example-master
> rimraf ./dist && webpack

keywords if/then/else require v5 option
(node:2480) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic,
 see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: 96268c6bb8d3b16b3592
Version: webpack 2.1.0-beta.27
Time: 6789ms
Asset       Size  Chunks             Chunk Names
src\app.component.d.ts  328 bytes          [emitted]
src\index.d.ts   65 bytes          [emitted]
src\polyfills.d.ts  480 bytes          [emitted]
src\app.module.d.ts   37 bytes          [emitted]
src\main.d.ts   26 bytes          [emitted]
app.96268c6bb8d3b16b3592.js     3.5 MB       0  [emitted]  app
node_modules\ngx-quill\index.d.ts   37 bytes          [emitted]
node_modules\ngx-quill\src\quill.module.d.ts   39 bytes          [emitted]
node_modules\ngx-quill\src\quill-editor.component.d.ts    1.91 kB          [emitted]
 index.html  528 bytes          [emitted]
 [331] ./src async 160 bytes {0} [built]
    + 601 hidden modules

ERROR in [default] C:\Users\Jack\Documents\ang2\ngx-quill-example-master\node_modules\@types\node\index.d.ts:50:13
All declarations of 'iterator' must have identical modifiers.

-------------------------------------

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Jack\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.4.1
3 info using node@v6.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle exmplate-ngx-quill@0.0.0~prebuild: exmplate-ngx-quill@0.0.0
6 silly lifecycle exmplate-ngx-quill@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle exmplate-ngx-quill@0.0.0~build: exmplate-ngx-quill@0.0.0
8 verbose lifecycle exmplate-ngx-quill@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle exmplate-ngx-quill@0.0.0~build: PATH: C:\Users\Jack\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Jack\Documents\ang2\ngx-quill-example-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\HP SimplePass\x64;C:\Program Files (x86)\HP SimplePass\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Git\cmd;C:\Users\Jack\AppData\Roaming\npm\node_modules\compass;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5\Doctrine extensions for PHP\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Go\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_102\bin;C:\Users\Jack\AppData\Local\Android\android-sdk\tools;C:\Users\Jack\AppData\Local\Android\android-sdk\platform-tools;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs\;C:\Users\Jack\AppData\Roaming\npm\node_modules\compass;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Jack\AppData\Local\.meteor\;C:\Go\bin;C:\Users\Jack\AppData\Local\Microsoft\WindowsApps;C:\Users\Jack\AppData\Local\Yarn\.bin;C:\Users\Jack\AppData\Roaming\npm
10 verbose lifecycle exmplate-ngx-quill@0.0.0~build: CWD: C:\Users\Jack\Documents\ang2\ngx-quill-example-master
11 silly lifecycle exmplate-ngx-quill@0.0.0~build: Args: [ '/d /s /c', 'rimraf ./dist && webpack' ]
12 silly lifecycle exmplate-ngx-quill@0.0.0~build: Returned: code: 2  signal: null
13 info lifecycle exmplate-ngx-quill@0.0.0~build: Failed to exec build script
14 verbose stack Error: exmplate-ngx-quill@0.0.0 build: `rimraf ./dist && webpack`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Jack\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Jack\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid exmplate-ngx-quill@0.0.0
16 verbose cwd C:\Users\Jack\Documents\ang2\ngx-quill-example-master
17 verbose Windows_NT 10.0.14393
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jack\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 verbose node v6.10.0
20 verbose npm  v4.4.1
21 error code ELIFECYCLE
22 error errno 2
23 error exmplate-ngx-quill@0.0.0 build: `rimraf ./dist && webpack`
23 error Exit status 2
24 error Failed at the exmplate-ngx-quill@0.0.0 build script 'rimraf ./dist && webpack'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the exmplate-ngx-quill package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     rimraf ./dist && webpack
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs exmplate-ngx-quill
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls exmplate-ngx-quill
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]

**Comment by KillerCodeMonkey** [comment]
thanks, i updated the package.json and set an older, fixed @types/node version.

Hope this helps in combination with your node version.

**Comment by spiritguide7** [comment]
Thanks! It's working perfectly now.

Can you enlighten me about custom fonts?

styles.css:
@import 'https://fonts.googleapis.com/css?family=Roboto';
@import 'https://fonts.googleapis.com/css?family=Sofia';
@import 'https://fonts.googleapis.com/css?family=Inconsolata';
@import 'https://fonts.googleapis.com/css?family=Ubuntu';

There fonts show up in other places in the app

import * as Quill from 'quill';
in component constructor:

 const FontAttributor = Quill.import('formats/font');
    FontAttributor.whitelist = [
      'sofia', 'roboto', 'inconsolata', 'ubuntu'
    ];
    Quill.register(FontAttributor, true);

css:
 quill-editor {
      display: block;
}
.ng-invalid {
  border: 1px dashed red;
}
.ql-font-roboto {
  font-family: 'Roboto';
}
.ql-font-sofia {
  font-family: 'Sofia';
}
.ql-font-inconsolata {
  font-family: 'Inconsolata';
}
.ql-font-ubuntu {
  font-family: 'Ubuntu';
}

HTML:

 <span class="ql-formats">
       <select class="ql-font" [title]="'Font'">
        <option selected></option>
        <option value="roberto"></option>
        <option value="sophia"></option>
        <option value="inconsolata"></option>
        <option value="ubuntu"></option>
      </select>

Result:

All 5 Font Dropdowns show up as 'San Serif!!!

Thanks
