### ISSUE TITLE
Quill edit not show control

### ISSUE THREAD

**Issue by phantanthanh1996** [KillerCodeMonkey/ngx-quill-example#10]
Hi, I am installing quill but when i deploy, i don't see any control in editor, pls help me.
**
![image](https://user-images.githubusercontent.com/26193725/46187473-f956b300-c30d-11e8-941c-a65ac1562308.png)
**

**Comment by KillerCodeMonkey** [comment]
Any logs in the JS console?



phantanthanh1996 <notifications@github.com> schrieb am Fr., 28. Sep. 2018,
06:02:
