### ISSUE TITLE
Unable to bind and update HTML value of editor programmatically 

### ISSUE THREAD

**Issue by raj07krishna** [KillerCodeMonkey/ngx-quill-example#1046]
I am having small issue in updating HTML value of editor while patching. My implementation is to highlight special characters and word to show user. Whenever I try to patch value of form-control with HTML code, editor always just take inner HTML and disregards all the tags and styling. Please guide what I am missing and how can I achieve it. I have attached my example which has same code base ngx-quill-example. 

Repo URL - https://github.com/raj07krishna/ngx-quill-highlight

Thanks for you time.

**Comment by KillerCodeMonkey** [comment]
quilljs allows only known styles and formats. i guess you have to register a custom format for your "highlight" class or at least whitelisting it.

https://quilljs.com/guides/how-to-customize-quill/#customizing-attributors
