### ISSUE TITLE
something mess up

### ISSUE THREAD

**Issue by guypeled1** [KillerCodeMonkey/ngx-quill-example#105]
Hi,
i added the default editor and it doesn't work.
this is what that happen:
https://prnt.sc/oxo39e
https://prnt.sc/oxo3hg

how can i solve this?

**Comment by KillerCodeMonkey** [comment]
check out the ngx-quill readme. you missed import the quill.core.css and quill.snow.css ;-)

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/9f76d62c0af22ff999de19b1da0d473d61c9b528/angular.json#L25
