### ISSUE TITLE
Remove Default P Tag around Img

### ISSUE THREAD

**Issue by codemystyle** [KillerCodeMonkey/ngx-quill-example#1076]
Hello, 

By default quill places p tag, want to achieve something like below. 

Could someone help me on this.

**Current Behavior.**

<p>blah blah blah</p>

<p>img src=""></p>

<p>blah blah blah</p>

**Expected Behavior:** 

<p>blah blah blah</p>

img src="">

<p>blah blah blah</p>

similar issue here - https://css-tricks.com/snippets/wordpress/remove-paragraph-tags-from-around-images/

**Comment by KillerCodeMonkey** [comment]
just ask this at quilljs repo :)

**Comment by KillerCodeMonkey** [comment]
PS you need to wrap your multiline code in triple backticks (in new lines) to get it formatted.
for single line code just use single backticks
