### ISSUE TITLE
Module '"quill"' has no default export

### ISSUE THREAD

**Issue by lilworks** [KillerCodeMonkey/ngx-quill-example#11]
I'm trying to implement your exemple in my cli project

I get the following error due to import Quill from 'quill';
`Module '"quill"' has no default export`

I add the scripts in my angular.json
  ```
          "scripts": [
             ...
              "./node_modules/ngx-quill/bundles/ngx-quill.umd.js",
              "./node_modules/quill/dist/quill.js",
              ...
            ],
```

**Comment by KillerCodeMonkey** [comment]
checkout this demo repo ;)
https://github.com/KillerCodeMonkey/ngx-quill-angular-cli
