### ISSUE TITLE
can not import ImageResize from 'quill-image-resize-module'

### ISSUE THREAD

**Issue by EnochGao** [KillerCodeMonkey/ngx-quill-example#12]
Hello, I am using angular4. Do I need npm install quill-image-resize-module before starting? After installation, I can't import ImageResize from 'quill-image-resize-module'; it says `Could not find a declaration file for module 'quill-image-resize-module'. 'C:/Users/Ying/Desktop/work /node_modules/quill-image-resize-module/image-resize.min.js' implicitly has an 'any' type.`

**Comment by KillerCodeMonkey** [comment]
Simply Check the package.json and App.component.ts ... It is working in
this example repo.

Check ngx-quill repo readme and the linked Demo Page. ;)

Am So., 18. Nov. 2018, 09:28 hat Enoch Gao <notifications@github.com>
geschrieben:

**Comment by EonchGao** [comment]
I am using angular/cli1.7.4. I have installed the following dependencies, but still can't reference.
`   "@types/quill": "^1.3.10",
    "ngx-quill": "^4.1.0",
    "quill": "1.3.6",
    "quill-image-resize-module": "^3.0.0",
    "quill-mention": "^2.0.5",`

**Comment by EonchGao** [comment]
In your app.compontent.ts file, when I put the mouse in import ImageResize from 'quill-image-resize-module', I am also prompted that the module cannot be found. But the strange thing is that it can run

**Comment by KillerCodeMonkey** [comment]
Strange but AS Long it is running and building ;). Maybe your IDE is not
refreshing your typings?

Am So., 18. Nov. 2018, 10:11 hat Enoch Gao <notifications@github.com>
geschrieben:
