### ISSUE TITLE
MatQuill component and BrowserModule

### ISSUE THREAD

**Issue by PhotonicDev** [KillerCodeMonkey/ngx-quill-example#1291]
BrowserModule is not necessary to be imported for mat-quill component module, since it just re-exports CommonModule, you should just use CommonModule, since angular is complaining about multiple imports of BrowserModule.

**Comment by KillerCodeMonkey** [comment]
do you mind to send a pr for that?

**Comment by KillerCodeMonkey** [comment]
thanks for the pr
