### ISSUE TITLE
Edit button not working when wrapped in mat-form-field

### ISSUE THREAD

**Issue by forbeshawkins** [KillerCodeMonkey/ngx-quill-example#1292]
Hi

Thanks for ngx-quill!

When you place a mat-quill inside a mat-form-field, am finding the'edit' button on the link popup no longer works. The click handler on mat-form-field seems to get in the way. 

Can work around it by adding click handlers in mat-quill.ts. Along the lines of this:

```
<ng-container *ngIf="toolbarPosition === 'top'">
<div quill-editor-element *ngIf="!preserve" (click)="$event.stopPropagation()"></div>
 <pre quill-editor-element *ngIf="preserve" (click)="$event.stopPropagation()"></pre>
</ng-container>
```

Not sure if this is the best solution though?

thanks

**Comment by KillerCodeMonkey** [comment]
there are many issues when using with material ui. if it is in form fields, tabs or what ever.

so if a workaround is working for you. DO IT!

**Comment by KillerCodeMonkey** [comment]
BTW: i have never really used material ui with angular. so the whole example module is just contribution work and "guessing around" by me.
