### ISSUE TITLE
For those who need help with the toolbar list, here it is ;)

### ISSUE THREAD

**Issue by sandeepsuvit** [KillerCodeMonkey/ngx-quill-example#13]
<div quill-editor-toolbar>
    <span class="ql-formats">
      <button type="button" class="ql-bold"></button>
      <button type="button" class="ql-italic"></button>
      <button type="button" class="ql-underline"></button>
      <button type="button" class="ql-strike"></button>
   </span>
    <span class="ql-formats">
      <button type="button" class="ql-blockquote"></button>
      <button type="button" class="ql-code-block"></button>
   </span>
    <span class="ql-formats">
      <button type="button" class="ql-header" value="1"></button>
      <button type="button" class="ql-header" value="2"></button>
   </span>
    <span class="ql-formats">
      <button type="button" class="ql-list" value="ordered"></button>
      <button type="button" class="ql-list" value="bullet"></button>
   </span>
    <span class="ql-formats">
      <button type="button" class="ql-script" value="sub"></button>
      <button type="button" class="ql-script" value="super"></button>
   </span>
    <span class="ql-formats">
      <button type="button" class="ql-indent" value="-1"></button>
      <button type="button" class="ql-indent" value="+1"></button>
   </span>
    <span class="ql-formats">
      <button type="button" class="ql-direction" value="rtl"></button>
   </span>
    <span class="ql-formats">
      <select class="ql-size">
         <option value="small"></option>
         <option selected="selected"></option>
         <option value="large"></option>
         <option value="huge"></option>
      </select>
   </span>
    <span class="ql-formats">
      <select class="ql-header">
         <option value="1"></option>
         <option value="2"></option>
         <option value="3"></option>
         <option value="4"></option>
         <option value="5"></option>
         <option value="6"></option>
         <option selected="selected"></option>
      </select>
   </span>
    <span class="ql-formats">
      <select class="ql-color">
         <option selected="selected"></option>
         <option value="#e60000"></option>
         <option value="#ff9900"></option>
         <option value="#ffff00"></option>
         <option value="#008a00"></option>
         <option value="#0066cc"></option>
         <option value="#9933ff"></option>
         <option value="#ffffff"></option>
         <option value="#facccc"></option>
         <option value="#ffebcc"></option>
         <option value="#ffffcc"></option>
         <option value="#cce8cc"></option>
         <option value="#cce0f5"></option>
         <option value="#ebd6ff"></option>
         <option value="#bbbbbb"></option>
         <option value="#f06666"></option>
         <option value="#ffc266"></option>
         <option value="#ffff66"></option>
         <option value="#66b966"></option>
         <option value="#66a3e0"></option>
         <option value="#c285ff"></option>
         <option value="#888888"></option>
         <option value="#a10000"></option>
         <option value="#b26b00"></option>
         <option value="#b2b200"></option>
         <option value="#006100"></option>
         <option value="#0047b2"></option>
         <option value="#6b24b2"></option>
         <option value="#444444"></option>
         <option value="#5c0000"></option>
         <option value="#663d00"></option>
         <option value="#666600"></option>
         <option value="#003700"></option>
         <option value="#002966"></option>
         <option value="#3d1466"></option>
      </select>
      <select class="ql-background">
         <option value="#000000"></option>
         <option value="#e60000"></option>
         <option value="#ff9900"></option>
         <option value="#ffff00"></option>
         <option value="#008a00"></option>
         <option value="#0066cc"></option>
         <option value="#9933ff"></option>
         <option selected="selected"></option>
         <option value="#facccc"></option>
         <option value="#ffebcc"></option>
         <option value="#ffffcc"></option>
         <option value="#cce8cc"></option>
         <option value="#cce0f5"></option>
         <option value="#ebd6ff"></option>
         <option value="#bbbbbb"></option>
         <option value="#f06666"></option>
         <option value="#ffc266"></option>
         <option value="#ffff66"></option>
         <option value="#66b966"></option>
         <option value="#66a3e0"></option>
         <option value="#c285ff"></option>
         <option value="#888888"></option>
         <option value="#a10000"></option>
         <option value="#b26b00"></option>
         <option value="#b2b200"></option>
         <option value="#006100"></option>
         <option value="#0047b2"></option>
         <option value="#6b24b2"></option>
         <option value="#444444"></option>
         <option value="#5c0000"></option>
         <option value="#663d00"></option>
         <option value="#666600"></option>
         <option value="#003700"></option>
         <option value="#002966"></option>
         <option value="#3d1466"></option>
      </select>
   </span>
    <span class="ql-formats">
      <select class="ql-font">
         <option selected="selected"></option>
         <option value="serif"></option>
         <option value="monospace"></option>
      </select>
   </span>
    <span class="ql-formats">
      <select class="ql-align">
         <option selected="selected"></option>
         <option value="center"></option>
         <option value="right"></option>
         <option value="justify"></option>
      </select>
   </span>
    <span class="ql-formats">
      <button type="button" class="ql-clean"></button>
   </span>
    <span class="ql-formats">
      <button type="button" class="ql-link"></button>
      <button type="button" class="ql-image"></button>
      <button type="button" class="ql-video"></button>
   </span>
</div>

**Comment by darshanDevrai** [comment]
@sandeepsuvit ,
 Thanks man. You have saved my day:)

**Comment by KillerCodeMonkey** [comment]
Nice thats how Open Source should Work :)

darshanDevrai <notifications@github.com> schrieb am Mo., 11. März 2019,
21:31:
