### ISSUE TITLE
Error angular 15

### ISSUE THREAD

**Issue by rodolfodecarvalho** [KillerCodeMonkey/ngx-quill-example#1300]
In the angular 15 version it is all broken.

https://github.com/rodolfodecarvalho/editor

![image](https://user-images.githubusercontent.com/58558609/208754502-5edd4a30-8b6b-4ecd-8018-fa5b2e40b242.png)

**Comment by KillerCodeMonkey** [comment]
Just include the css correctly.

Seems like quilljs css is missing.

Rodolfo de Carvalho Guerra ***@***.***> schrieb am Di., 20.
Dez. 2022, 20:56:

**Comment by KillerCodeMonkey** [comment]
Follow the installation instructions in ngx-quill readme search for similar issues and check the code of the examples, before opening issues. Thanks
