### ISSUE TITLE
Font Styles

### ISSUE THREAD

**Issue by Gssaini73** [KillerCodeMonkey/ngx-quill-example#136]
Is there any way to add more font styles in it. Because by default there are only three (sans, sans serif and monospace). I want to add styles like Arial, Times New Roman etc.

**Comment by KillerCodeMonkey** [comment]
Checkout this example Repo there is an Editor with custom Fonts ;-).

You need to add additional css-classes and add the new Fonts to quill.



Gssaini73 <notifications@github.com> schrieb am Fr., 20. Sep. 2019, 07:16:

**Comment by Gssaini73** [comment]
Thanks a lot
