### ISSUE TITLE
Saving editor text

### ISSUE THREAD

**Issue by davvit** [KillerCodeMonkey/ngx-quill-example#14]
hi, Thanks for directing me to detailed example @KillerCodeMonkey.

I am trying to save the editor text when the user clicks on a button; that's on a toolbar.
I added the button and click listener/handler.

When I click the button the editor object is null in my component. i suspect its angular lifecycle issue but if there is a way to accomplish this using the toolbar APIs please let me know.

[StackBlitz](https://stackblitz.com/edit/angular-gwtebm-quill-test)

![image](https://user-images.githubusercontent.com/4433698/50262322-3b0b6d00-03d6-11e9-8811-3322d57329b3.png)

**Comment by KillerCodeMonkey** [comment]
IS IT possible to Share the Code Link of Stack Blitz?

But You should know that a Native Javascript Event Like a click listener
does Not have the quill Editor instance AS property.

Just Listen to the ngx Output onEditorCreated there You get the quill
instance.
And then use this in You Button click listener.

But If You use ngModel or formControl You have the latest Editor value
automatically stored in a variable. So on click your button, just send the
value of your model or formControl :). No need to Grab and Store the Editor
instance

Am Do., 20. Dez. 2018, 04:38 hat davvit <notifications@github.com>
geschrieben:

**Comment by davvit** [comment]
the link should take you to the editor... https://stackblitz.com/edit/angular-gwtebm-quill-test
I will try the ngModel way looks easy enough to do. Thanks again.
