### ISSUE TITLE
Editing link does not work when mat-quill is located in mat-form-field

### ISSUE THREAD

**Issue by arko0x** [KillerCodeMonkey/ngx-quill-example#1435]
Hello,
while using ngx-quill-example repository I noticed, that after creating a link it can't be edited for all Material Quill examples, toolbar just disappears instead.

Steps to reproduce

Use mat-quill component inside mat-form-field.
Mark text as link
Try to edit link

**Comment by KillerCodeMonkey** [comment]
feel free to contribute. since this is only an example repo how a mat quill solution could look like i will not invest much time to solve some material ui specific problems
