### ISSUE TITLE
Disable a part of text editing

### ISSUE THREAD

**Issue by celia-ms** [KillerCodeMonkey/ngx-quill-example#1477]
Hi!,

I have a question about if exit any way to disable a part of the text edit if we found a token for example: "'$name$' or '$address$'".

Hi '$name$',
I send you the order to '$address$'

The idea is to load RTF document and be able to change only the text that has no tokens.

I tried to do it in different ways but I don't found the solution.

**Comment by KillerCodeMonkey** [comment]
you can add custom listeners to changes of the content. there you get the change and can check if a "token" was changed -> then undo it.
