### ISSUE TITLE
How to display editor data in HTML

### ISSUE THREAD

**Issue by harshitraghav** [KillerCodeMonkey/ngx-quill-example#15]
I have saved the data typed in the editor to my database and it gets saved in a HTML format with tags. Now, when I'm trying to display that data in my HTML it comes along with those HTML tags. How I can remove those tags and show only the data.

**Comment by KillerCodeMonkey** [comment]
Eeehm You need to use the innerhtml property of a htmlnode to Set HTML
content simply using {{ content }}, will Not Work.

But the creator of quilljs recommends to use a quill Editor in readonly
Mode and without a toolbar to Show the result.

Am Mo., 14. Jan. 2019, 19:24 hat Harshit Raghav <notifications@github.com>
geschrieben:

**Comment by harshitraghav** [comment]
Oh I did't know that but How I'm supposed to use it in readonly mode?

**Comment by KillerCodeMonkey** [comment]
Simply Check the readme Here and search for readonly ;).

Or Take a Look in the example repo.

If You Go this way. You do Not need to Store füll HTML Strings. You can Set
the Format to json and simple Store and Work with quill json representation
of the content ;).

You can Set the content Format via an input property, Like readonly Mode ;).

Am Mo., 14. Jan. 2019, 19:38 hat Harshit Raghav <notifications@github.com>
geschrieben:

**Comment by harshitraghav** [comment]
Yeah! Thanks got the solution ;)
