### ISSUE TITLE
Add custom table 

### ISSUE THREAD

**Issue by quan1997ap** [KillerCodeMonkey/ngx-quill-example#1512]
Hi team, I want to add custom table to ngx-quill. Looks like it's currently not supported.
How can i do it.
Thanks.
--- Sorry about my english ---

**Comment by rayhan999** [comment]
Hey @KillerCodeMonkey , Any update on HTML table feature? I really need it.

**Comment by quan1997ap** [comment]
@rayhan999 - "tables will be supported with quilljs v2. but since it is not stable it is not supported with ngx-quill. you can try to ignore that and install the dev quilljs" he said that and I'm trying.
