### ISSUE TITLE
Quill with angular 16 

### ISSUE THREAD

**Issue by Guddoo812** [KillerCodeMonkey/ngx-quill-example#1695]
I am trying to use quill with angular 16 but it is not visible. Can you give any example of quill editor with angular 16

**Comment by KillerCodeMonkey** [comment]
Just Look in the commit history ;-)

Am 3. März 2024 04:22:34 MEZ schrieb Guddoo812 ***@***.***>:

**Comment by Guddoo812** [comment]
> Just Look in the commit history ;-) Am 3. März 2024 04:22:34 MEZ schrieb Guddoo812 ***@***.***>:
> […](#)
> I am trying to use angular 16 but it is not visible. Can you give any example of quill editor with angular 16 -- Reply to this email directly or view it on GitHub: #1695 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>


Can You Plaese Provide Me link. I am unable to find

**Comment by KillerCodeMonkey** [comment]
Ahhh you are right. I recreated the repo to have a clean base with latest cli.

But in General it is more or less the same.

Install angular 16. Quill v1, @types/quill v1 and ngx-quill 23

**Comment by Guddoo812** [comment]
> Ahhh you are right. I recreated the repo to have a clean base with latest cli.
> 
> But in General it is more or less the same.
> 
> Install angular 16. Quill v1, @types/quill v1 and ngx-quill 23

I have angular version 16.0.3 in my package.json
node version 16.20.2
npm version 6.14.3
quill version 1.3.7
types/quill version 1.3.10
ngx-quill version 23.0.0 

the editor is not visible, can you please help in giving me correct working versions

**Comment by KillerCodeMonkey** [comment]
nope i think you should able to do it on your own. you can even just follow the install instructions of the ngx-quill repo https://github.com/KillerCodeMonkey/ngx-quill/tree/v23.0.2
