### ISSUE TITLE
Precompile code for GitHub pages

### ISSUE THREAD

**Issue by qjnr** [KillerCodeMonkey/ngx-quill-example#17]
I think it would be nice if you precompiled the code and created a GH pages branch, so people can view the project without having to download and compile it themselves. I think this would be really nice, because it's an example application, so if people could view it immediately in their browser it would be very handy.

This is just an idea, if you disagree that's fine too.

**Comment by qjnr** [comment]
Sorry, I couldn't find a link to the page so I thought it didn't exist. Turns out it does, actually. My bad.

**Comment by KillerCodeMonkey** [comment]
Actually IT IS Linked in the readme ;)

Am Mi., 30. Jan. 2019, 21:06 hat Quintus Rijpstra <notifications@github.com>
geschrieben:

**Comment by qjnr** [comment]
Oh, now I see it! Awesome work on this project, BTW
