### ISSUE TITLE
Switching from code-block to h2 or ordered list does not work

### ISSUE THREAD

**Issue by szlezakbartosz** [KillerCodeMonkey/ngx-quill-example#1726]
When trying to switch from code-block into h2, h1 gets selected instead. Same if you try to switch from code-block into ordered list, the bullet list will get selected instead. The Stackblitz is with the ancient Angular version, but it behaves the same in my project using Angular 16. It works fine with straight QuillJs though.

[Stackblitz demo](https://stackblitz.com/edit/ngx-quill-angular-okpscr)

Demo:
![chrome-capture-2024-4-3](https://github.com/KillerCodeMonkey/ngx-quill-example/assets/97099991/525d2112-02c7-4351-876b-74c6fe7326d8)

Repro steps:
1. insert code-block into editor
2. click on h2/ordered list
3. h1/bullet list gets selected instead

Correct behaviour:
The toolbar item that was clicked should be selected (h2/ordered list)

**Comment by KillerCodeMonkey** [comment]
i can not reproduce it in my demo with quill v2 rc4 https://killercodemonkey.github.io/ngx-quill-example/

**Comment by KillerCodeMonkey** [comment]
so i guess it may have something to be with your custom config or quill changes between v1 and v2. because i am doing nothing special. just wrapping quilljs

**Comment by KillerCodeMonkey** [comment]
i can reproduce it here: https://v1.quilljs.com/playground/ so it is a general bug in quill v1

**Comment by szlezakbartosz** [comment]
> i can reproduce it here: https://v1.quilljs.com/playground/ so it is a general bug in quill v1

You're right, maybe I was doing something wrong because I was no able to reproduce with straigth Quill, but succeeded now. Thanks for checking it out and sorry for the trouble :)
