### ISSUE TITLE
Contribute proposition

### ISSUE THREAD

**Issue by Yexan** [KillerCodeMonkey/ngx-quill-example#177]
Hi @KillerCodeMonkey 

Would you like me to add a more complex exemple ? 
I never used quill before I ran into your `ngx-quill` lib (which is awesome) and faced some issues with quill to make custom toolbar and create Attributors because there is not a lot of docs.

If you're ok with it, how would you like me to contribute ?
A new folder to separate completely the exemple and handle dependancies otherwise or should I limit the exemple in functionalities to fit in your `src/app/componentXXXX` ?

👍 for your work and quick reply on every issues !

**Comment by KillerCodeMonkey** [comment]
simply feel free and do it :). i never thought the small lib will get to 35k downloads a month.

So yes, i create a new folder for each component.

In general i would like to add something like 
https://storybook.js.org/docs/guides/guide-angular/

to the project, where you can toggle each options or set the properties in the UI, without having that many examples.

**Comment by Yexan** [comment]
Hi Bengt,
I haven't had the time this week but I keep it in mind !
You can leave the issue closed no worries 😊

**Comment by KillerCodeMonkey** [comment]
no rush. i see this "issue" more than a initial question if you can do it. and so you can. if you do it, is your problem 😉. there is no due date
