### ISSUE TITLE
 ERROR TypeError: Cannot read property 'modules' of undefined  at  e.ngAfterViewInit

### ISSUE THREAD

**Issue by Ravslee** [KillerCodeMonkey/ngx-quill-example#18]
I was trying to run the demo, but I  got the following issue in the console

main.04d82b49341e3ab3a15f.js:1 ERROR TypeError: Cannot read property 'modules' of undefined
    at e.ngAfterViewInit (main.04d82b49341e3ab3a15f.js:1)

**Comment by KillerCodeMonkey** [comment]
yep, ia m currently working on it. :)

**Comment by Ravslee** [comment]
> yep, ia m currently working on it. :)

Can I help you with this ?? I am really interested in in this project :)

**Comment by KillerCodeMonkey** [comment]
nope, this is some strange things occured because of ng prod build  and my config provider, but thanks :)
