### ISSUE TITLE
can't delete the pic

### ISSUE THREAD

**Issue by cywforce** [KillerCodeMonkey/ngx-quill-example#1867]
![微信图片_20241108224649](https://github.com/user-attachments/assets/dfc1d12c-a97a-4791-952e-1d287cc9d581)
![微信图片_20241108224955](https://github.com/user-attachments/assets/4fcb6e91-3698-49cb-96a1-c06a8af9217b)

**Comment by cywforce** [comment]
![Uploading 微信图片_20241108224955.png…]()

**Comment by KillerCodeMonkey** [comment]
solved in latest quill image resizor version. but check the readme for necessary changes.
