### ISSUE TITLE
How to embed getty images

### ISSUE THREAD

**Issue by harshitraghav** [KillerCodeMonkey/ngx-quill-example#19]
How do I embed getty images in the editor. When i try to embed using tag property it shows embedded code as a code rather than showing it as a image.

**Comment by KillerCodeMonkey** [comment]
What is "getty" Image. Just Checkout quilljs API Docs how to instert
content.

If you want to add HTML your have to Convert IT or use the deprecated
DangerouslyInsertHtml function.



Harshit Raghav <notifications@github.com> schrieb am So., 17. März 2019,
09:07:

**Comment by harshitraghav** [comment]
I mean Images from the Getty website. They give us code to embed their images, code looks like this:
<a id='JXiZgZtbSjdfSpj_2pqBnw' class='gie-single' href='http://www.gettyimages.in/detail/1136401098' target='_blank' style='color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;'>Embed from Getty Images</a><script>window.gie=window.gie||function(c){(gie.q=gie.q||[]).push(c)};gie(function(){gie.widgets.load({id:'JXiZgZtbSjdfSpj_2pqBnw',sig:'M3TBl-UEsUKtEaQ-Nq5eH_uiu4qg8CWfmLG5ChEvrvQ=',w:'594px',h:'396px',items:'1136401098',caption: true ,tld:'in',is360: false })});</script><script src='//embed-cdn.gettyimages.com/widgets.js' charset='utf-8' async></script>
When I try to enter this code using the tag section, it doesn't show us the image but only the code. Although image is supposed to be shown after entering this code.

**Comment by KillerCodeMonkey** [comment]
I do Not think that this works or IS possible with quilljs.

Please Close this issue Here and Checkout the quilljs repo.

The creators of quilljs can Help you out, i think.

Harshit Raghav <notifications@github.com> schrieb am So., 17. März 2019,
17:23:
