### ISSUE TITLE
The font button not work

### ISSUE THREAD

**Issue by yupengfei** [KillerCodeMonkey/ngx-quill-example#20]
https://killercodemonkey.github.io/ngx-quill-example/

When choose 'Monospace', nothing happened

**Comment by KillerCodeMonkey** [comment]
And Other Fonts?
Maybe this IS a Problem, because i have an example Editor with custom fonts
and These are overriding the Base Fonts.

于鹏飞 <notifications@github.com> schrieb am Fr., 22. März 2019, 10:45:

**Comment by KillerCodeMonkey** [comment]
should be fixed :). Thanks for opening this issue 👍
