### ISSUE TITLE
 How to add emojis to the default editor?

### ISSUE THREAD

**Issue by simplew11** [KillerCodeMonkey/ngx-quill-example#21]
hi KillerCodeMonkey：
 How to add emojis to the default editor?
Thank!

**Comment by KillerCodeMonkey** [comment]
you can find how to pass it as module config here:

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/emoji/emoji.component.ts#L13

And you can pass `QuillModule.forRoot()` (https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/app.module.ts#L49) a default config.

https://github.com/KillerCodeMonkey/ngx-quill#global-config

> The QuillModule exports the defaultModules if you want to extend them :).
