### ISSUE TITLE
use quill-image-resize-module  Uncaught TypeError: Cannot read property 'imports' of undefined

### ISSUE THREAD

**Issue by simplew11** [KillerCodeMonkey/ngx-quill-example#22]
hi KillerCodeMonkey:
step : npm i quill-image-resize-module
code:
![image](https://user-images.githubusercontent.com/25675703/55786436-cc6a3080-5ae6-11e9-9ee6-194e221bc83f.png)
error:
![image](https://user-images.githubusercontent.com/25675703/55786467-e277f100-5ae6-11e9-9629-22210d9dea39.png)
Thank!

**Comment by KillerCodeMonkey** [comment]
not an issue of quill or ngx-quill or of the example repo. just use google... or search through existing issues in the ngx-quill.

just a hint:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/angular.json#L33

image resize expects the quill object to be globally available... you can find even a commit in this repo, how i integrated image-resize -.-

**Comment by nehadhiman6** [comment]
Same Issue.. Did you find any solution?

**Comment by KillerCodeMonkey** [comment]
just simply check my code here in the repo ... it is working. ;-)

**Comment by nehadhiman6** [comment]
> just simply check my code here in the repo ... it is working. ;-)

Where?

**Comment by zel-prodi** [comment]
> > just simply check my code here in the repo ... it is working. ;-)
> 
> Where? please provide link Thank you

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/angular.json#L33

**Comment by rgantla** [comment]
I've had the same problem ... turns out, i missed to include `"node_modules/quill/dist/quill.min.js"` in the `scripts `array of `angular.json` file in my project.
