### ISSUE TITLE
Does Quill support copy and paste image into the editor?

### ISSUE THREAD

**Issue by simplew11** [KillerCodeMonkey/ngx-quill-example#23]
Hi KillerCodeMonkey:
Does Quill support copy and paste image into the editor?
Thanks!

**Comment by KillerCodeMonkey** [comment]
ehm maybe quill converts image to base64 strings.

https://github.com/quilljs/quill/pull/821
https://github.com/quilljs/quill/issues/137
https://github.com/quilljs/quill/issues/2478

you should check quilljs repo for that. :)
