### ISSUE TITLE
Lazy-load Highlight.js for Quill Syntax Module in Lazy-Loaded Angular Module?

### ISSUE THREAD

**Issue by KeithGillette** [KillerCodeMonkey/ngx-quill-example#269]
This example project shows loading the Highlight.js script and its CSS in `index.html`. We are using `ngx-quill` in lazy-loaded modules and would prefer to lazy-load HighlightJS, as well, in order to optimize application load time. However, our attempts to do so have failed. We always get the error `'Syntax module requires highlight.js. Please include the library on the page before Quill.'` when configuring `syntax: true`. Any tips on lazy-loading Highlight.js?

**Comment by KillerCodeMonkey** [comment]
I do Not know If this is possible, because quilljs needs it on the global
Context.

So it would be hacky to put and remove it on your own there.

I would just load IT globally, maybe through the angular json or custom
webpack.

And in General you should ASK this in the highlight.js Repo or Stack
overflow.





Keith Gillette <notifications@github.com> schrieb am Do., 26. Dez. 2019,
17:44:

**Comment by KeithGillette** [comment]
Thanks for the fast reply, @KillerCodeMonkey! I'll ask elsewhere. If Quill expects Highlight.js in the global context, do you happen to know what name it expects? Is it `hljs`?

**Comment by KillerCodeMonkey** [comment]
Yes, I think this is the global namespace of highlight.js.





Keith Gillette <notifications@github.com> schrieb am Do., 26. Dez. 2019,
18:10:

**Comment by KeithGillette** [comment]
Thanks, again @KillerCodeMonkey . We're investigating [using the `highlightChildren` directive from `ngx-highlightjs` imported in our lazy-loaded module](https://github.com/MurhafSousli/ngx-highlightjs/issues/72#issuecomment-462739525) as a solution, but I think I also found a way to initialize the Syntax module of Quill in a lazy-loaded scenario using this suggestion from [Quill issue #2130](https://github.com/quilljs/quill/issues/2130#issuecomment-494183592)

In `angular.json`:
```json
scripts: {
	"input": "node_modules/highlight.js/lib/highlight.js",
	"lazy": true,
	"bundleName": "highlight"
}
```

In a routing guard method for the lazy-loaded module:
```typescript
import('highlight.js').then((highlightModule: { default: { highlightAuto: Function } }) => {
	const Syntax = Quill.import('modules/syntax');
	Syntax.DEFAULTS = {
	highlight: function (text: string): string {
		const result = highlightModule.default.highlightAuto(text);
		return result.value;
		}
	};
});
```

**Comment by Mikkal24** [comment]
@KeithGillette Thanks for providing that insight. Since the SEO on this page is more highly ranked than anything else I figured I'd share my spin off solution. 

Instead of creating a route guard I just added the import inside the `loadChildren` function like so:


```ts
  {
    path: "blog",
    loadChildren: () =>
      import("./modules/screens/blog/blog.module").then(async (m) => {
        window.hljs = await import("highlight.js"); //assigns highlight.js to the global namespace as hljs
        return m.BlogModule;
      }),
  },
```

thanks again guys!
