### ISSUE TITLE
How do I reset the quill delta

### ISSUE THREAD

**Issue by Fayde** [KillerCodeMonkey/ngx-quill-example#3]
Angular 4 reactive forms w/ quill I'm having issues with patching in rich text into the quill editor. The problems don't happen the first time but on subsequent patches on the same form it will strip out <p> tags and such inside the body

I don't have an easy way to reproduce this to show you but maybe this description will give me a hint how I can reset the quill delta between form loads

edit: sorry this should probably be in the main repo

**Comment by KillerCodeMonkey** [comment]
duplictated by https://github.com/KillerCodeMonkey/ngx-quill/issues/53

please only add issues associated with the example repo here.
