### ISSUE TITLE
Custom emoji-blot example

### ISSUE THREAD

**Issue by rocketkittens** [KillerCodeMonkey/ngx-quill-example#308]
Please provide example for how to implement custom emoji blot when using emoji example.

I'm unable to find a way to use a custom instance of Quill (`import Quill from 'quill';`) together with `<quill-editor>`

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/emoji/emoji.component.ts

https://github.com/contentco/quill-emoji

**Comment by KillerCodeMonkey** [comment]
Ehm you are linked my Demo working with quill Emoji?


And there are Others examples with a custom Word count Module or Others
Third Party modules... So there is an example die the Thing you asked for.

Just Share a Demo repo or Stackblitz, how you tried IT :)

Alan <notifications@github.com> schrieb am So., 2. Feb. 2020, 05:35:

**Comment by rocketkittens** [comment]
I gave up because i realized emoji-blot is the representation of an emoji inside the editor and not the `#emoji-palette` element which i am actually targeting. I managed to register and use various modules using the following syntax:

```
npm install --save @types/quill

import Quill from 'quill';
import 'quill-mention'; // pre-registered module
import BlotFormatter from 'quill-blot-formatter';
import 'quill-emoji/dist/quill-emoji.js';
Quill.register('modules/blotFormatter', BlotFormatter);
...
this.modules = {
  'mention': {
    allowedChars: /^[A-Za-z\sÅÄÖåäö]*$/,
    mentionDenotationChars: ["@", "#"],
    source: async function(searchTerm: string, renderList: any) {
      const matchedPeople = await suggestPeople(searchTerm);
      renderList(matchedPeople);
    }
  },
  'blotFormatter': true,
  'emoji-shortname': false,
  'emoji-textarea': false,
  'emoji-toolbar': true,
}
```

**Comment by KillerCodeMonkey** [comment]
thanks for sharing your solution :)
