### ISSUE TITLE
Triggering bold method manually

### ISSUE THREAD

**Issue by ialex90** [KillerCodeMonkey/ngx-quill-example#4]
Hi there,

I opened a ticket for this yesterday but I think it has been removed. You told me to ask quill js team as this is only a wrapper, and I saw in their doc that they have this functionality, see this link:https://quilljs.com/docs/api/#formatting

So, it would be like: `quill.formatText(0, 5, 'bold', true);      // bolds 'hello'
`
I am asking if you as the author of this lib if you have exposed this through the lib api, as I didn't see it but I might missed it.

Thanks,

**Comment by KillerCodeMonkey** [comment]
You can listen to the "onEditorCreated" output, there You get the quill
instance AS eventdata. Checkout the docs of this repo and the demo repo.

Am 17.01.2018 11:19 vorm. schrieb "Alejandro" <notifications@github.com>:

**Comment by ialex90** [comment]
Thanks for the quick answer.

I accessed the instance in another way, but same result, I saw there is a bold function but its not working as I'd expect, doesn't change/update the content. For instance, this: 

`$event.editor.delta.ops[1].attributes.bold = false // it was true, represent a bold word`

and then updating like:

`$event.editor.update()
`
Not working.

**Comment by KillerCodeMonkey** [comment]
hey, ditd you get it working?

maybe you could try to trigger angular change detection or something else
