### ISSUE TITLE
How to work with input properties.?

### ISSUE THREAD

**Issue by prabhpahul** [KillerCodeMonkey/ngx-quill-example#421]
Thank you for such an amazing project.

I've implemented ngx-quill angular material form control version. There are multitude of input properties like minLength, maxLength and trimOnValidation which works with default quill-editor but are not working on mat-quill. 

I've seen disabled mixin been created but not sure what is ideology behind it. I want to extend all the basic functionality of inputs in quill-editor to mat-editor.

**Comment by prabhpahul** [comment]
I handle it by adding Validate function of base class to custom form field validator.

**Comment by KillerCodeMonkey** [comment]
Check my Demo repo there is a possible Implementation with Material ui.

But in general i am Not usig Material ui with angular. And my components
are Just there to Work without IT in general.

The easiest Thing would be to Just Style The Editor to Look Something like
Material. So you do Not have to implement everything again in your own.

Prabhpahul Singh <notifications@github.com> schrieb am Di., 26. Mai 2020,
21:20:

**Comment by KillerCodeMonkey** [comment]
Ah okay^^. You were Faster. :)

Bengt Weiße <bengtler@googlemail.com> schrieb am Mi., 27. Mai 2020, 07:00:

**Comment by prabhpahul** [comment]
You have done some amazing work. Yea I did add that functionality on the top of implementation you have for the material. 
Thank you again.
