### ISSUE TITLE
Dropdown issue when overlapping next text field

### ISSUE THREAD

**Issue by bfrunza** [KillerCodeMonkey/ngx-quill-example#445]
When using the bubble version of the editor, if the dropdown options are going over the next input field, it's impossible to select the option. Somehow, the input field is the one taking the click, and not the dropdown

**Comment by KillerCodeMonkey** [comment]
You should mention this at the quilljs repo. ;-).

Bogdan Frunza <notifications@github.com> schrieb am Do., 16. Juli 2020,
16:02:
