### ISSUE TITLE
Handle inline css stying withing HTML

### ISSUE THREAD

**Issue by kasparov112000** [KillerCodeMonkey/ngx-quill-example#478]
Hi,
    Thanks for the library.  I want quill to handle large html file with inline styling, I am having an issue where some of the styling is not working, 	for instance text-decoration:underline:
	
	<p style="margin-top:0pt; margin-bottom:8pt; font-size:0.83em">
				<a name="_WCvcc_1_dd_XC__3_60690d_60690d_60690d"><span style="font-family:Georgia; font-weight:bold; text-decoration:underline">SCOPE OF  SERVICES, DELIVERABLES, AND TIMING.</span></a>

Any assistance is appreciated,

**Comment by KillerCodeMonkey** [comment]
do you switched from class-based to inline styling?

**Comment by kasparov112000** [comment]
thanks but that seems complicated, is there a simple switch to inline styling ? so quill reads the inline styling already in the html document?

**Comment by KillerCodeMonkey** [comment]
nope. because quilljs just allows the formats it knows.
