### ISSUE TITLE
p tag is not shown line break in <quill-editor>

### ISSUE THREAD

**Issue by jaeyonghan-dev** [KillerCodeMonkey/ngx-quill-example#512]
i using the <quill-editor> tag.

i enter the 2 string include enter key.

e.x) 
one line (push enter key) 
two line

it is save the ```<p>one line</p><p>two line</p>``` in database.

then  i call this content at ```<quill-editor>```, it is not shown the line break.
expected show:
one line
two line

but editor is shown:
one linetwo line (but api resonse is <p>one line</p><p>two line</p>

how fix this problem?

**Comment by KillerCodeMonkey** [comment]
maybe just sharing a complete example to reproduce

**Comment by jaeyonghan-dev** [comment]
hi @KillerCodeMonkey  , 
api response is `<p>test</p><p>testtest</p><p>test</p>`

but the editor is not shown the line break(no line break)
![스크린샷 2020-09-28 오후 8 42 58](https://user-images.githubusercontent.com/69179097/94428294-72be6000-01cb-11eb-9d05-d1bc4028a248.png)

**Comment by KillerCodeMonkey** [comment]
sure... but like i wrote... i can not help you just with screenshots... 

i need to know how you set the editor content and so on...

**Comment by KillerCodeMonkey** [comment]
you can also check https://killercodemonkey.github.io/ngx-quill-example/ - "Format - HTML"

where i pass in html and it is shown correctly in the editor.

please check if you pass a valid html string (no escaped chars and so on)
