### ISSUE TITLE
using custom dropdown with all the default functionalities(bold,italic, etc)

### ISSUE THREAD

**Issue by chanderbhanpal** [KillerCodeMonkey/ngx-quill-example#518]
Hi ,

can we use custom dropdown as toolbar and default functionality at the same time . 

facing issue while using both 
vendor.js:284653 quill:toolbar ignoring attaching to nonexistent format ee <select class=​"ql-ee" style=​"display:​ none;​">​…​</select>​<option value=​"22">​</option>​</select>​
debug @ vendor.js:284653

as warning message and not binding the data  into it.
in ts file (angular 8) :
modules = {
    formula: false,
    toolbar:
    {
    container:  
    [      
      ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
      [{ 'header': 1 }, { 'header': 2 }],               // custom button values
      [{ 'list': 'ordered' }, { 'list': 'bullet' }],
      [{ 'script': 'sub' }, { 'script': 'super' }],     // superscript/subscript
      [{ 'indent': '-1' }, { 'indent': '+1' }],         // outdent/indent
      [{ 'direction': 'rtl' }],                         // text direction
      [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
      [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
      [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
      [{ 'font': [] }],
      [{ 'align': [] }],
      
      ['clean'],                                         // remove formatting button
 
      ['link', 'image', 'video']    ,
     [{ 'ee': ['22'] }],  // my dropdown
    ],
    handlers: {
      'customControl': () => { console.log('customControl was clicked') }
    }
  }
  };

   <quill-editor  formControlName="mailHtml" [modules]="modules"  [styles]="{height: '200px'}"
  
      (onEditorChanged)="changedEditor($event)">
     
    </quill-editor>

**Comment by KillerCodeMonkey** [comment]
Nope i do Not think so it is supported by quilljs

chanderbhanpal <notifications@github.com> schrieb am Mo., 5. Okt. 2020,
17:42:

**Comment by chanderbhanpal** [comment]
thank you
