### ISSUE TITLE
load html content is not correctly shown in quill-editor 

### ISSUE THREAD

**Issue by jaeyonghan-dev** [KillerCodeMonkey/ngx-quill-example#521]
hello .  
i can't solve this problem. 
https://github.com/KillerCodeMonkey/ngx-quill-example/issues/512#issue-710154891
then i question more.

this is my code.

.html
```
<quill-editor
                  (onEditorCreated)="getEditorInstance($event)"
                  [theme]="'snow'"
                  [format]="'html'"
                  [modules]="isView ? {toolbar : false} : { toolbar: [ [{ 'font': [] }], [{ 'header': 1 }, { 'header': 2 }],  [{ 'size': ['small', false, 'large', 'huge'] }],  [{ 'color': [] }, { 'background': [] }], ['bold', 'italic', 'underline', 'strike'],   [{ 'align': [] }],['blockquote', 'code-block'], [{ 'list': 'ordered'}, { 'list': 'bullet' }], ['image', 'link']] }"
                  [placeholder]="'insert text"
                  [style]="{'padding-right': '4px', 'padding-bottom': '4px', 'height': '200px', 'min-height': '200px', 'overflow-y': 'visible', 'resize': 'vertical', 'min-height': '200px'}"
                  [bounds]="'self'"
                  formControlName= "content">
                </quill-editor>
```
load content to below.
formControlName= "content" is contains 
`content: "<p>test</p><p>testtest</p><p>test</p>"`

i see in console.log() in getEditorInstance function, console.log is ...
editor > "delta" is shown. 

if i convert delta to html , is it shown in editor correctly?
if correctly, how can i set html editor?
i wait your comment. 🙏 

![스크린샷 2020-10-08 오전 11 23 38](https://user-images.githubusercontent.com/69179097/95407724-c44bb500-0958-11eb-9309-1a61eb43f803.png)

getEditorInstance funtion is contains this code.
```

getEditorInstance(editorInstance) {
    **console.log('quill>>',editorInstance);** // <- i print log here
    if (!this.isView) {
      const toolbar = editorInstance.getModule('toolbar');
      toolbar.addHandler('image', (_) => {
        const input = document.createElement('input');
        input.setAttribute('type', 'file');
        input.setAttribute('accept', 'image/*');
        input.click();
        this.renderer.listen(input, 'change', (evt) => {
          const f: File = evt.path[0].files[0];
          const reader = new FileReader();
          reader.onload = (evt2: ProgressEvent) => {
            if (f) {
              this.uploadImage(editorInstance, f);
            } else {
              this.modalService.confirm({
                ...
              });
            }
          };
          reader.readAsDataURL(f);

        });
      });
    }
  }
```

**Comment by KillerCodeMonkey** [comment]
why converting delta to html on your own?

if you want to programmatically change the editor content -> just use patchValue function of your formControl/formgroup and set new html string.

if you want to get the html content of the editor -> subscribe to changes of your formControl or listen on `OnContentChanged`output: https://github.com/KillerCodeMonkey/ngx-quill#outputs

there you get the current editor content as delta, text and html.

**Comment by jaeyonghan-dev** [comment]
unfortunately, i can't solve this problem. 

in my db (mysql), content is saved **<p>test</p><p>testtest</p><p>test</p> .**
call this value in .ts file(call api )  it is same.  (alert(value) is same).

but `(onEditorCreated)="getEditorInstance($event)"` <- in this function, it is print different in console -> testtesttestest ....
(today operate test... ol , li ,ul tag is disappear) .

uhm.... i think format = "html" is not working.

i think it is solved saved in db value is corretly apper in quill-editor.
i hope help me.

parent source file define quill below.
```

const Link = Quill.import('formats/link');
Link.PROTOCOL_WHITELIST = ['https', 'http'];

class linkType extends Link {
  static create(value) {
    let node = super.create(value);
    value = this.sanitize(value);
    console.log('value: ', value);
    node.removeAttribute('target');
    return node;
  }

  format(name, value) {
    super.format(name, value);

    if (name !== this.statics.blotName || !value) {
      return;
    }
    this.domNode.removeAttribute("target");
  }
}

Quill.register(linkType);
```

**Comment by KillerCodeMonkey** [comment]
in general format html is working... because it is working in my demo repo when passing html strings as default value...

check for example the `Reactive Forms and patch value` editor on https://killercodemonkey.github.io/ngx-quill-example/

So guess something with your config is wrong.

i would try to remove all custom code from your side.
