### ISSUE TITLE
Tooltip for the text inside quill editor

### ISSUE THREAD

**Issue by SouravDey1996** [KillerCodeMonkey/ngx-quill-example#543]
Hi, can you please help me on how can we add a tooltip to a specific word inside the quill editor

**Comment by KillerCodeMonkey** [comment]
add your custom form/blot which adds a tooltip or e.g. a "title" html attribute.

checkout existing formats/blots.

like link format where a box opens to enter the link.
You could adapt it and enter the tooltip text and wrap it around the tooltip. 

e.g. a span with the tooltip text as title

But in general it is a quilljs question ;-)
