### ISSUE TITLE
Problem with mat form error state

### ISSUE THREAD

**Issue by JakaRua** [KillerCodeMonkey/ngx-quill-example#761]
After the first clearing of the input, the error-state does not work. It also doesn't work on your demo.

https://user-images.githubusercontent.com/10262515/123231532-f4d08080-d4e0-11eb-82fa-e171447f5616.mp4

**Comment by KillerCodeMonkey** [comment]
does it only not work for the material quill stuff?

**Comment by KillerCodeMonkey** [comment]
btw. for me it is working in chrome and firefox. There was a problem with the latest version of the examples. (JS errors where thrown).

So maybe this was the root cause. so just clear the cache and reload :)

**Comment by JakaRua** [comment]
I downloaded the project and deployed it locally. I fixed the errors so that everything started, but the result is the same. When the input is cleared for the first time on the material, the validation does not work, but when it is filled in and removed a second time, it does. And it is the material of the component that interests. I removed all unnecessary in the downloaded demo, left only the quill material and the result is the same (

**Comment by KillerCodeMonkey** [comment]
maybe you have installed something in your browser? like i said. it is working in my firefox and chrome

**Comment by KillerCodeMonkey** [comment]
now i got it. for this maxLength validation you need to extend the MatQuill example implementation. seems like material ui does not support custom validation like ngx-quill does out of the box.

**Comment by KillerCodeMonkey** [comment]
i changed the example, that only required is used. keep in mind that "MatQuill" is only a minimal example that shows how it could be used with material.. it is not a production ready solution
