### ISSUE TITLE
Argument of type 'ElementRef<any>' is not assignable to parameter of type 'Injector'. Property 'get' is missing in type 'ElementRef<any>' but required in type 'Injector'.

### ISSUE THREAD

**Issue by begandroide** [KillerCodeMonkey/ngx-quill-example#775]
Hi, recently I installed ngx-quill and extends the QuillEditorBase to implement a mat-form-field that supports reactive forms with error handling.

Im facing a issue related with the extension of quill-base-editor, locally i dont have issues but when i upload my application to Azure Static Website y made a build and i has this output:
![image](https://user-images.githubusercontent.com/22018004/124493748-fbce7d00-dd83-11eb-9adf-0bd07382e397.png)

I followed the guides to extend a matformcontrol: [https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/mat-quill](https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/mat-quill).

Which could be the error?

Regards

**Comment by begandroide** [comment]
stranger because if i build locally i dont has errors of TS

**Comment by KillerCodeMonkey** [comment]
Keep in mind in The latest Release The Interface Changes of quillbase.

IT IS using Injector as first Element in constructor and Not elementref.

I think your ci installs different ngx-quill Versions.

In ci you should use `npm ci` or `yarn Install --frozen-lock-file`

**Comment by begandroide** [comment]
Thanks you @KillerCodeMonkey, the issue was the update of ngx-quill and the changes of constructor.

Happens that i has in package.json: `"ngx-quill": '^14.0.0'`, since the last version is the 14.1.2, the cli install the last one. (Always we can learn more :))

Thanks again, in a few hours i will make a PR to update the example.
