### ISSUE TITLE
How to add custom button with existing toolbar

### ISSUE THREAD

**Issue by manisha-lanke** [KillerCodeMonkey/ngx-quill-example#8]
I want to add custom button in existing toolbar.
Now only existing toolbar is display or only custom button is display.
please suggest.

**Comment by KillerCodeMonkey** [comment]
this is only my demo repo ;)

YOu have to pass a complete toolbar object than :).

checkout the quilljs documentation (https://quilljs.com/docs/quickstart/) for the default config.
