### ISSUE TITLE
example no work with angular cli 6.

### ISSUE THREAD

**Issue by josepfdc** [KillerCodeMonkey/ngx-quill-example#9]
there are many errors this example with angular cli 6.

Please, could you update this example with angular 6 or make a new example for angular cli 6

Thank you in advance for your help !!!

Regards,
Frank

**Comment by KillerCodeMonkey** [comment]
Eeehm this is Not helpful AT all... And this example does Not Use angular
cli???  It uses simple webpack and is not There to include it Info another
project.

josepfdc <notifications@github.com> schrieb am Mi., 23. Mai 2018, 22:21:

**Comment by josepfdc** [comment]
Hi my friend!  :-)
I made a example very simple that work perfectly without "quill-image-resize-module" package.

here is the example:

https://stackblitz.com/edit/angular6-ngxquill-resize-image

I think the error is angular cannot import this package "quill-image-resize-module"

```
Cannot read property 'imports' of undefined
Evaluating https://unpkg.com/quill-image-resize-module@3.0.0/image-resize.min.js

```

Please, could you tell me what we can do to resolve this issue.

Thank you in advance for your help

Frank

**Comment by KillerCodeMonkey** [comment]
you need to make sure Quill is set on the window-object.
because the resize-modules uses Quill via `window.Quill`

In Webpack you can solve this to add 'window.Quill': 'pathToQUilljs' to the webpack provide Plugin
